name: time_tracking_app
description: Time tracking app.

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  kiwi: ^4.1.0
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  flutter_form_bloc: ^0.31.0
  flutter_offline: ^3.0.1
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  kiwi_generator: ^4.1.0

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset:  assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 200
        - asset:  assets/fonts/Roboto/Roboto-Light.ttf
          weight: 400
        - asset:  assets/fonts/Roboto/Roboto-Black.ttf
          weight: 500
        - asset:  assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 600
        - asset:  assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 800
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 900